if(MYGUI_BUILD_TEST_APP)
	add_subdirectory(TestApp)
endif()

if(MYGUI_BUILD_ADVANCED_DEMOS)
	add_subdirectory(Demo_ChildAttach)
	add_subdirectory(Demo_Delegates)
	add_subdirectory(Demo_GraphView)
	add_subdirectory(Demo_HyperTextBox)
	add_subdirectory(Demo_ItemBox_Info)
	add_subdirectory(Demo_Layers)
	add_subdirectory(Demo_RTTLayer)
	add_subdirectory(Demo_RotatingSkin)
	add_subdirectory(Demo_Spline)
	add_subdirectory(Demo_TextureAnimations)
	add_subdirectory(Demo_TreeControl)
endif()
