add_subdirectory(Common)

add_subdirectory(UnitTest_Delegates)
add_subdirectory(UnitTest_AttachDetach)
add_subdirectory(UnitTest_ComboBox)
add_subdirectory(UnitTest_Controllers)
add_subdirectory(UnitTest_ItemBox)
add_subdirectory(UnitTest_ImageBox)
add_subdirectory(UnitTest_MenuControl)
add_subdirectory(UnitTest_MultiList)
add_subdirectory(UnitTest_TabControl)
add_subdirectory(UnitTest_WidgetGeometry)
add_subdirectory(UnitTest_InputManager)
add_subdirectory(UnitTest_EditBox)
add_subdirectory(UnitTest_Scrolling)
add_subdirectory(UnitTest_Text)
add_subdirectory(UnitTest_RectangularSkin)
add_subdirectory(UnitTest_RotatingPolygonalSkin)
add_subdirectory(UnitTest_ListBehaviour)
add_subdirectory(UnitTest_Resources)
add_subdirectory(UnitTest_Rendering)
add_subdirectory(UnitTest_Layers)
add_subdirectory(UnitTest_Canvas)
