add_subdirectory(Common)

add_subdirectory(UnitTest_Delegates)
add_subdirectory(UnitTest_Sigslot)
add_subdirectory(UnitTest_AttachDetach)
add_subdirectory(UnitTest_ComboBox)
add_subdirectory(UnitTest_Controllers)
add_subdirectory(UnitTest_ItemBox)
add_subdirectory(UnitTest_ImageBox)
add_subdirectory(UnitTest_MenuControl)
add_subdirectory(UnitTest_MultiList)
add_subdirectory(UnitTest_TabControl)
add_subdirectory(UnitTest_WidgetGeometry)
add_subdirectory(UnitTest_InputManager)
add_subdirectory(UnitTest_EditBox)
add_subdirectory(UnitTest_Scrolling)
add_subdirectory(UnitTest_Text)
add_subdirectory(UnitTest_RectangularSkin)
add_subdirectory(UnitTest_RotatingPolygonalSkin)
add_subdirectory(UnitTest_ListBehaviour)
add_subdirectory(UnitTest_Resources)
add_subdirectory(UnitTest_XmlDocument)
add_subdirectory(UnitTest_DataStream)
add_subdirectory(UnitTest_Rendering)
add_subdirectory(UnitTest_Layers)
add_subdirectory(UnitTest_Window)
add_subdirectory(UnitTest_DragDrop)
add_subdirectory(UnitTest_ProgressBar)
add_subdirectory(UnitTest_Canvas)

if (MYGUI_BUILD_PLATFORM_TESTS)
    add_subdirectory(UnitTest_Platform)
    if (MYGUI_RENDERSYSTEM EQUAL 4)
        add_subdirectory(UnitTest_OpenGLPlatform)
    elseif (MYGUI_RENDERSYSTEM EQUAL 7)
        add_subdirectory(UnitTest_OpenGL3Platform)
    elseif (MYGUI_RENDERSYSTEM EQUAL 8 AND NOT EMSCRIPTEN)
        add_subdirectory(UnitTest_OpenGLESPlatform)
    elseif (MYGUI_RENDERSYSTEM EQUAL 11)
        add_subdirectory(UnitTest_OsgPlatform)
    elseif (MYGUI_RENDERSYSTEM EQUAL 10)
        add_subdirectory(UnitTest_VulkanPlatform)
    endif ()
endif ()
