set(CPACK_PACKAGE_VERSION ${MYGUI_VERSION})
set(CPACK_PACKAGE_VERSION_MAJOR ${MYGUI_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${MYGUI_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${MYGUI_VERSION_PATCH})

set(CPACK_INSTALL_CMAKE_PROJECTS "${MYGUI_BINARY_DIR}" "MYGUI" "ALL" "/")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "MyGUI - fast, flexible and simple GUI")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "MYGUI")
set(CPACK_PACKAGE_NAME "MYGUI")
set(CPACK_PACKAGE_VENDOR "")

set(CPACK_RESOURCE_FILE_LICENSE "${MYGUI_SOURCE_DIR}/COPYING")

set(CPACK_PACKAGE_CONTACT "MYGUI Team <altren@list.ru>")

set(CPACK_NSIS_EXTRA_INSTALL_COMMANDS "WriteRegStr \\\${WriteEnvStr_RegKey} \\\"MYGUI_HOME\\\" $INSTDIR")

include(CPack)
