name: Basic Build

on: [push, pull_request]

jobs:
  build:
    name: build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v7

      - name: Install build dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq cmake libfreetype6-dev libsdl2-dev libsdl2-image-dev

      - name: Install build dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install cmake freetype

      - name: Install SDL2 via vcpkg (macOS/windows)
        if: runner.os != 'Linux'
        run: vcpkg install sdl2

      - name: Install deps via vcpkg (windows)
        if: runner.os == 'Windows'
        run: vcpkg install freetype sdl2

      - name: Configure
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE="$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DMYGUI_HIGH_LEVEL_WARNINGS=TRUE \
          -DMYGUI_BUILD_TOOLS=FALSE \
          -DMYGUI_BUILD_UNITTESTS=FALSE \
          -DMYGUI_RENDERSYSTEM=1

      - name: Build
        run: cmake --build build --config RelWithDebInfo --parallel
